export const usePermissions = () => ({
  role: 'admin',
  loading: false,
  edit: true,
  delete: true,
  manageUsers: false,
  manageGroups: false,
  manageInvitations: false,
  viewAuditLog: false,
  viewSettings: false,
  isAdmin: false,
  canEdit: true,
  canDelete: true,
  canManageUsers: false,
  canManageGroups: false,
  canManageInvitations: false,
  canViewAuditLog: false,
  canViewSettings: false,
})
